id = "barbenheimer"
name = "Barbenheimer Theme"
version = "0.0.1"
schema_version = 1
authors = ["Jayvic San Antonio <codes@jayvicsanantonio.dev>"]
description = "A theme inspired by the Internet phenomenon of the same name. It combines the pink and playful aesthetics of Barbie with the dark and dramatic tones of Oppenheimer."
repository = "https://github.com/jayvicsanantonio/barbenheimer-zed-theme"
